##############################################################
##
##	makefile of the ann library
##	2003-03-07 by ShanLanshan
##############################################################

CC		=	g++
PATH_INCL	=	./
INCL		=	-I$(PATH_INCL)

.PHONY: clean all

all:

clean:
